### ISSUE TITLE
Delete link to FOI Wiki

### ISSUE THREAD

**Issue by Gemmamysoc** [mysociety/belgium-theme#10]
Email from team:

During the chat today I talk about a link to http://foiwiki.com/foiwiki/index.php/Internal_reviews which is not interesting for Belgian users.
 
This link is accessible on the second paragraph of the page "Request an internal review" (of each request). The anchor is something like "Details".
 
Could you delete this link for Transparencia ?

**Comment by lizconlan** [comment]
Ugh, this is in the `followups/_followup.html.erb` template so there are implications for future upgrades.

This is part of the advisory text that appears above the telling people they have a right to complain so taking it out seems like not a great idea (unless people in Belgium don't have a right to complain, I guess) - should it link to something else instead*?:

![screen shot 2016-09-30 at 11 28 21](https://cloud.githubusercontent.com/assets/27760/18988958/1bedfc84-8701-11e6-973d-4c2babbaf485.png)

"If you are dissatisfied by the response you got from the public authority, you have the right to complain (details)." (the word details links to the foiwiki.com page)

---
*does not alter the fact that we'd have to hack the template but might provide a better outcome for users of the site

**Comment by Gemmamysoc** [comment]
Message from Belgian team:

Two possibility : Delete the link or point to multiple links (due to the structure of Belgium there is not a unique link for information).
 
The different links are :
 
- Fédéral : http://www.ibz.rrn.fgov.be/fr/commissions/publicite-de-ladministration/
- Wallonie et Fédération Wallonie-Bruxelles : http://www.cada-wb.be/
- Bruxelles : http://be.brussels/a-propos-de-la-region/le-ministere-de-la-region-de-bruxelles-capitale/secretariat-general/gestion-des-ressources-humaines/direction-de-la-fonction-publique-1/commission-dacces-aux-documents-administratifs

**Comment by lizconlan** [comment]
To keep the link (Christophe has removed it in the translation file for now), we could have the links on one of the help pages and link to that instead of foiwiki.

**Comment by Gemmamysoc** [comment]
Sounds good to me. I'll let Christophe know so they can factor that in to their work on the Help pages

**Comment by lizconlan** [comment]
The link has been removed by not including it in the Transifex string

We may be able to add it in later by adding a custom help page (or, if appropriate add a section to a current help page) with the 3 links in (as above) and linking to this new section instead of straight to the page (TBC whether that would be a theme customisation or a Transifex hack)
