### ISSUE TITLE
Update help pages

### ISSUE THREAD

**Issue by lizconlan** [mysociety/belgium-theme#11]
(When copy arrives)

**Comment by Gemmamysoc** [comment]
They should send these on Monday 10th Oct

**Comment by lizconlan** [comment]
ToDo - ask for missing translated copy for contact us page (i.e. bits that show/hide depending on how you got to the page)

**Comment by lizconlan** [comment]
Reopened - pushed to site, awaiting partner feedback

**Comment by garethrees** [comment]
Don't think anything else has come through, so closing in favour of specific tickets for any fixes

**Comment by garethrees** [comment]
Help pages were linked to here https://groups.google.com/a/mysociety.org/d/msg/alaveteli/xmPYb6tSGbc/AhYseXwzAwAJ
