### ISSUE TITLE
Enable all new Pro features

### ISSUE THREAD

**Issue by garethrees** [mysociety/belgium-theme#110]
Requires https://github.com/mysociety/belgium-theme/issues/109

No pricing

## `ENABLE_ALAVETELI_PRO`

Main documentation at https://alaveteli.org/docs/pro/

- [x] Make sure Alaveteli Pro Transifex resource is translated
- [x] Configure [POP poller](https://alaveteli.org/docs/customising/config/#production_mailer_retriever_method) (https://github.com/mysociety/sysadmin/issues/1347)
- [x] ~Create `pro`, `pro_admin` roles~
  * _Should_ be done automatically since [#4029](https://github.com/mysociety/alaveteli/issues/4029)
- [x] Decide on self-service access or invite-only
  * Missing from docs ([#5839](https://github.com/mysociety/alaveteli/issues/5839))
- [x] Add `/help/pro` translations
  * Missing from docs ([#5834](https://github.com/mysociety/alaveteli/issues/5834))
  * Translations in [Google Drive](https://drive.google.com/drive/u/1/folders/1xIpyI50OacEg3t2TmePUmqVxWR4gm2Zk)
- [x] [Configure](https://alaveteli.org/docs/pro/) pro-related settings
- [x] Create first `pro_admin` through the console
  * Missing from docs ([#5835](https://github.com/mysociety/alaveteli/issues/5835))
- [x] Check all cron tasks and daemons are enabled
  * **TODO:** Check that there's no extra manual work to do to enable these

**Comment by JenMysoc** [comment]
Confirmed: invite only

**Comment by garethrees** [comment]
Link to the thread https://groups.google.com/u/1/a/mysociety.org/g/alaveteli/c/bXfPwKtHMps

**Comment by gbp** [comment]
The existing admins already had the pro_admin role.

All the other remaining tasks have been completed.

**Comment by garethrees** [comment]
Anything extra we need to do to consider this closed?
