### ISSUE TITLE
Generate previews of all emails sent by the site

### ISSUE THREAD

**Issue by lizconlan** [mysociety/belgium-theme#15]
And send to Belgium team so they can see how the translated text will look.

**Comment by lizconlan** [comment]
Generated and sent. Waiting to see if it needs to be re-run before closing, either to adjust the format or to view with new translations.

**Comment by garethrees** [comment]
Haven't heard anything back from them so closing

**Comment by lizconlan** [comment]
there was only one comment which was due to my mistake of including the test user with HTML in their name which made it look like the template was including raw HTML
