### ISSUE TITLE
Logged in bar breaks with long(er) translations

### ISSUE THREAD

**Issue by lizconlan** [mysociety/belgium-theme#20]
In a 1000px+ window:

![capture1](https://cloud.githubusercontent.com/assets/27760/19357646/6ddd102a-916a-11e6-9887-a3639033840f.jpg)

And just before it jumps to the mobile view, with the language switcher displayed:

![screen shot 2016-10-13 at 17 40 20](https://cloud.githubusercontent.com/assets/27760/19358079/5036e85a-916c-11e6-8e6d-ae0f893c4200.png)

It just about fits in English:

![screen shot 2016-10-13 at 17 43 13](https://cloud.githubusercontent.com/assets/27760/19358124/991e6714-916c-11e6-98c9-76a29e37fbe0.png)

**Comment by garethrees** [comment]
Think this was the best we could get in https://github.com/mysociety/alaveteli/issues/2989

**Comment by lizconlan** [comment]
Moving this to New for now as it's not going to interfere with the launch

**Comment by garethrees** [comment]
Closing because it works as expected – can't really do much else about this at this point.
