### ISSUE TITLE
Add sentence to email that goes to users when authority hasn't responded in time

### ISSUE THREAD

**Issue by Gemmamysoc** [mysociety/belgium-theme#28]
New sentence highlighted: 
 
NAME OF THE AUTHORITY est en retard.

Ils n'ont pas répondu à votre demande de NAME OF THE REQUEST, comme requis par la loi.

Vous pouvez :
 
**- Soit saisir la Commission d'Accès aux Documents Administratifs (CADA) (plus d'infos https://transparencia.be/help/cada)**
- Soit envoyer un message à NAME OF THE AUTHORITY afin de leur rappeler de répondre à votre demande (lien vers le formulaire http://transparencia.be/c/m3m8vmwj0ib4s7x8811).

-- L'équipe de Transparencia

**Comment by garethrees** [comment]
via https://groups.google.com/a/mysociety.org/forum/#!topic/alaveteli/kxlPfl-tHfw

**Comment by lizconlan** [comment]
Note to implementer - the second link in the text is to the new_followup page, don't just copy-paste it :)

**Comment by lizconlan** [comment]
ToDo:

 - [ ] make simplest possible change
 - [ ] generate an example email
 - [ ] make a translatable version? (will result in theme-specific translations)

**Comment by garethrees** [comment]
Here's how you [generate theme translations](https://github.com/mysociety/alaveteli/wiki/Generate-theme-translations). I don't think we have a theme project for them, so that will need creating.

**Comment by lizconlan** [comment]
To generate an example email (adapted from `translation.rake`):

```
def write_email(email, email_description, output_file)
  mail_object =  MailHandler.mail_from_raw_email(email.to_s)
  output_file.write("\n")
  output_file.write("Description of email: #{email_description}\n")
  output_file.write("Subject line: #{mail_object.subject}\n")
  output_file.write("\n")
  if mail_object.parts.empty?
    mail_object.header.fields.each do |field|
      output_file.write("#{field.name}: #{Mail::Encodings.value_decode(field)}\n")
    end
    output_file.write("\n")
    output_file.write(mail_object.decoded)
  else
    mail_object.parts.each do |part|
      output_file.write("Message part **\n")
      output_file.write(part.body.to_s)
    end
  end
  output_file.write("\n")
  output_file.write("********\n")
end


info_request = InfoRequest.find(108)
output_file = File.open('./sample_email.txt', 'w')

overdue_alert_email = RequestMailer.overdue_alert(info_request, info_request.user)
write_email(overdue_alert_email,
            'Telling the requester that the public body is late in replying',
             output_file)
```

**Comment by lizconlan** [comment]
Example generate email:

```
Ministry of Sensible Walks est en retard.

Ils n'ont pas répondu à votre demande de Liberté d'accès à l'information Cheap v1agra rapidement, comme requis par la loi.

Vous pouvez :

 - Soit saisir la Commission d'Accès aux Documents Administratifs (CADA) (plus d'infos https://transparencia.be/help/cada)

 - Soit envoyer un message à Ministry of Sensible Walks afin de leur rappeler de répondre à votre demande (lien vers le formulaire http://alaveteli.10.10.10.30.xip.io/c/g9y2puwvglmrfsxee3a).

-- L'équipe de Transparencia
```
