### ISSUE TITLE
Text change to https://transparencia.be/help/cada

### ISSUE THREAD

**Issue by Gemmamysoc** [mysociety/belgium-theme#29]
Change text on [this page:](https://transparencia.be/help/cada)

Now : 
Transparencia n'est pas encore prévu pour le traitement des demandes d’avis à la CADA. Ces demandes doivent être envoyées directement à la CADA par mail ou par courrier.
 
Transmettez à la CADA le lien vers votre demande sur le site Transparencia ou imprimez cette demande afin que la CADA puisse avoir accès à l’ensemble de vos échanges avec l’autorité publique.

New text : 
Transparencia n'est pas encore prévu pour le traitement des demandes d’avis à la CADA. Ces demandes doivent être envoyées directement à la CADA par mail ou par courrier. Par contre vous pouvez envoyer votre demande de reconsidération à l'autorité publique via Transparencia. Pour cela cliquez sur le lien "Demander une reconsidération" qui se trouve au bas de la page de votre demande.
 
Ensuite, et le même jour, transmettez à la CADA le lien vers votre demande sur le site Transparencia ou imprimez cette demande afin que la CADA puisse avoir accès à l’ensemble de vos échanges avec l’autorité publique et la preuve que vous avez bien envoyé la demande de reconsidération.

**Comment by garethrees** [comment]
Via https://groups.google.com/a/mysociety.org/forum/#!topic/alaveteli/YVZydqcC34I
