### ISSUE TITLE
Everything is bold on RequestController#show

### ISSUE THREAD

**Issue by garethrees** [mysociety/belgium-theme#32]
![screen shot 2016-12-05 at 10 29 43](https://cloud.githubusercontent.com/assets/282788/20881765/c8cb6fc4-bad5-11e6-90b0-3a8221e1482c.png)

**Comment by lizconlan** [comment]
https://transparencia.be/request/registre_de_securite_des_ecoles_12

May be specific to the overdue status

**Comment by lizconlan** [comment]
Yep, missing closing bracket in translation of  "Response to this request is <strong>delayed</strong>."

**Comment by lizconlan** [comment]
oh and also `Response to this request is <strong>long overdue</strong>.`

**Comment by lizconlan** [comment]
fixed by translation hotfix 0.25.0.22
