### ISSUE TITLE
Add addition to Help pages

### ISSUE THREAD

**Issue by Gemmamysoc** [mysociety/belgium-theme#33]
Message from partner: 

"Could you make a change in the second part of the page [https://transparencia.be/help/conditions](https://transparencia.be/help/conditions) ?
 
**OLD :**
Droit de rectification :
Conformément aux dispositions légales toutes les personnes peuvent faire rectifier, sans frais, les données qui les concernent et qui s'avéreraient inexactes, incorrectes ou incomplètes. Contactez-nous via info@transparencia.be afin d'être informé de la procédure de rectification.
 
**NEW :**
Droit de rectification :
Conformément aux dispositions légales toutes les personnes peuvent faire rectifier, sans frais, les données qui les concernent et qui s'avéreraient inexactes, incorrectes ou incomplètes. Contactez-nous via info@transparencia.be afin d'être informé de la procédure de rectification.
Responsable du traitement des données : Christophe Van Gheluwe - Place Van Meenen 3 bte 6 - 1060 Bruxelles - 0497 18 30 87.
 
It's en legal obligation to give the name and the address of the person who is responsible of the treatment of the personal data."

**Comment by lizconlan** [comment]
Changes deployed
