### ISSUE TITLE
Spelling mistake on help/about

### ISSUE THREAD

**Issue by garethrees** [mysociety/belgium-theme#44]
> We made a spelling mistake in the page https://transparencia.be/help/about in French.
>  
> The title "Que faire si je découvre une demande qui me semble innapropriée ?" is wrong.
>  
> "Que faire si je découvre une demande qui me semble inapropriée ?" is good.
>  
> Could you make the change?
>
> – https://groups.google.com/a/mysociety.org/forum/#!topic/alaveteli/mLQJiWo-rlg

**Comment by garethrees** [comment]
Update Christophe when fixed.

**Comment by lizconlan** [comment]
Done!
