### ISSUE TITLE
Missed translation in fr/help/unhappy

### ISSUE THREAD

**Issue by garethrees** [mysociety/belgium-theme#46]
> In the page https://transparencia.be/help/unhappy/transparence_des_mandats_liste_d_3
> 
> There is a sentence still in English in the French part of Transparencia : "... and then write a message asking the authority to review your request."
> 
> The translation in French is : "pour demander à l'autorité publique de reconsidérer votre demande".
> 
> – https://groups.google.com/a/mysociety.org/forum/#!topic/alaveteli/wfmhoEZWHsQ

**Comment by lizconlan** [comment]
Done!
