### ISSUE TITLE
Upgrade to 0.28

### ISSUE THREAD

**Issue by garethrees** [mysociety/belgium-theme#48]
Needs newer bundler

**Comment by lizconlan** [comment]
Depends on mysociety/alaveteli#3957

**Comment by garethrees** [comment]
- WDTK host: Bundler version 1.3.5
- Belgium host: Bundler version 1.1.4

**Comment by sagepe** [comment]
Bundler updated to packaged version `1.3.5-2` to match WDTK.

**Comment by lizconlan** [comment]
awesome, thanks @sagepe \o/

**Comment by lizconlan** [comment]
Deployed \o/
