### ISSUE TITLE
Text changes to Help pages

### ISSUE THREAD

**Issue by Gemmamysoc** [mysociety/belgium-theme#51]
Now in French  (https://transparencia.be/help/conditions): 
Responsable du traitement des données : Christophe Van Gheluwe - Place Van Meenen 3 bte 6 - 1060 Bruxelles - 0497 18 30 87.
 
New text in French : 
Responsable du traitement des données : Patrick Installé - Route Provinciale, 144 - 1480 Tubize.
 
Now in Dutch (https://transparencia.be/nl_BE/help/conditions): 
Verantwoordelijke voor de gegevensverwerking : Christophe Van Gheluwe - Meenenplein 3 bus 6 - 1060 Brussel.
 
New text in Dutch: 
Verantwoordelijke voor de gegevensverwerking : Patrick Installé - Route Provinciale, 144 - 1480 Tubize.

**Comment by lizconlan** [comment]
Close via ec3426cb1
