### ISSUE TITLE
Add User#postcode and User#province

### ISSUE THREAD

**Issue by garethrees** [mysociety/belgium-theme#55]
> we need that subdivision for a Huge FOI campaign in consortium with 6 newspaper. Next year is municipal election all over in Belgium.

>For the voters to have enough information about what their local politicians are doing.
We need to empower Transparencia users by municipality "Commune" and then by Province , to buid a community of FOI requestors that can share their work on the same authorithy (the "Commune")

https://groups.google.com/a/mysociety.org/forum/#!topic/alaveteli/c-1PdjddAdA

**Comment by lizconlan** [comment]
- [ ] Add Postcode and Province to the theme translations
- [ ] Add theme migration for new fields
- [ ] Customise sign-up form
- [ ] Check editing an existing profile

**Comment by lizconlan** [comment]
(May need some further discussion on translations - looks like there are a couple I may not have asked for yet and as I was late providing any form of context there may be some alterations)
