### ISSUE TITLE
Style the widget page to use Transparencia's colours

### ISSUE THREAD

**Issue by lizconlan** [mysociety/belgium-theme#68]
> I see that the Ask theEU widget shows nicely with their logo and name of their site
>
> Ours always display Alavetelli instead of Transparencia (.be) ..and with a wrong color (we would prefer the same backround color as Asktheu)
>
> Would it possible to adapt this widget display ?

Current (default) styling:

<img width="322" alt="screen shot 2017-12-18 at 18 21 19" src="https://user-images.githubusercontent.com/27760/34121264-53dd6fee-e420-11e7-98f6-94233061c08b.png">

AskTheEU:

<img width="321" alt="screen shot 2017-12-18 at 18 22 57" src="https://user-images.githubusercontent.com/27760/34121330-85c8409c-e420-11e7-8b1e-a3014fe44fe0.png">

**Comment by wrightmartin** [comment]
PR here https://github.com/mysociety/belgium-theme/pull/70
