### ISSUE TITLE
Add video to Transparencia homepage

### ISSUE THREAD

**Issue by Gemmamysoc** [mysociety/belgium-theme#78]
Partner would like this video to appear on homepage: https://www.youtube.com/watch?v=kOcNSNNK0ik as per AsktheEU and KiMitTud

**Comment by garethrees** [comment]
Context: https://groups.google.com/a/mysociety.org/forum/#!topic/alaveteli/46OWbAdfyyg

**Comment by wrightmartin** [comment]
Here's a quick mockup of how I'd do it 

![Uploading Screen Shot 2018-06-27 at 09.18.49.png…]()

**Comment by garethrees** [comment]
LGTM
