### ISSUE TITLE
Update Logo

### ISSUE THREAD

**Issue by garethrees** [mysociety/belgium-theme#87]
https://groups.google.com/a/mysociety.org/forum/#!topic/alaveteli/3O5wBamA8kw

Will need assets for

- Header logo
- Header 2x logo
- Opengraph logo
- Widget base

**Comment by wrightmartin** [comment]
> Hi Martin,
> 
> With Claude we have decided to use the new logo with the loop everywhere on the website of Transparencia.be (website, widget,...).
> 
> So, you could use the logo loop everywhere.
> 
> Many thanks.

**Comment by wrightmartin** [comment]
WIP here https://github.com/mysociety/belgium-theme/tree/issues/87-update-logo
