### ISSUE TITLE
Use the new logo on the widget page

### ISSUE THREAD

**Issue by lizconlan** [mysociety/belgium-theme#89]
Example page https://transparencia.be/request/826/widget/new

**Comment by garethrees** [comment]
I don't think it got missed: https://github.com/mysociety/belgium-theme/blob/5f310da96c5f448eb36bf060d4d40d85da5ab84d/app/assets/images/widget-base.png

It could be https://github.com/mysociety/alaveteli/issues/4719, or a varnish caching issue.

**Comment by lizconlan** [comment]
Hmm, the main image appeared right away so might be  mysociety/alaveteli#4719

**Comment by lizconlan** [comment]
Ah, was/is Varnish. Updating that and the opengraph one just in case

**Comment by lizconlan** [comment]
Fixed by `varnishadm "ban req.http.host == transparencia.be && req.url == /assets/widget-base.png"`
