### ISSUE TITLE
Edit 'Participate' banner if possible

### ISSUE THREAD

**Issue by Gemmamysoc** [mysociety/belgium-theme#9]
Edit as per this image:
![new-design](https://cloud.githubusercontent.com/assets/6806067/18951632/1acac36e-863e-11e6-93ba-aeffb49bf14e.jpg)
![logo-anticor](https://cloud.githubusercontent.com/assets/6806067/18951636/1d561d54-863e-11e6-9e3d-44989ad03cb0.gif)

**Comment by Gemmamysoc** [comment]
Text for banner: 

Participez (link to https://anticor.be/doku.php?id=participer:start) / Neem deel (link to https://www.anticor.be/doku.php?id=neemdeel:start)
Transparencia est un service d’Anticor Belgium (link to https://www.anticor.be/)

**Comment by lizconlan** [comment]
Have made the links turn orange on mouseover to match the highlight text on the homepage:

![screen shot 2016-10-07 at 11 52 21](https://cloud.githubusercontent.com/assets/27760/19187882/ffe2c242-8c85-11e6-9c5c-a22ea9a9ac1b.png)

We _could_ remove the underlining from the links as per the mockup image but I don't think it's clear that you can click on them, it just looks like an announcement:

![screen shot 2016-10-07 at 11 48 26](https://cloud.githubusercontent.com/assets/27760/19187670/bcaca0d4-8c84-11e6-9d01-231aa4fcccb2.png)
